server:
  port: 80
spring:
  application:
    name: gateway
  redis:
    host: 192.168.16.173
    port: 5379
    lettuce:
      pool:
        max-active: 2
        max-idle: 2
        max-wait: -1ms
        min-idle: 0
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.16.173:8848
    gateway:
      routes:
        - id: simple_route
          uri: https://www.baidu.com
          predicates:
            - Path=/baidu/**
          filters:
            - StripPrefix=1